### ISSUE TITLE
When playing multiple files, subtitle cache is not cleared on new file

### ISSUE THREAD

**Issue by himdel** [rumkex/osdb-mpv#3]
osdb-mpv doesn't seem to detect a new file has started playing when one presses Ctrl+F, causing subtitles for the previous episode to appear.

Steps to reproduce:

1. `mpv file1 file2`
1. when playing `file1`, press Ctrl+F
1. subtitles will get correctly downloaded and used
1. wait until `file2` starts playing, or skip to it
1. press Ctrl+F
1. subtitles for `file1` will get used (next in cache)

One has to manually cycle through the cache and then press Ctrl+F once again, for subtitles for `file2` to get downloaded.

**Comment by himdel** [comment]
mpv version: 0.22.0
osdb-mpv version: cce2e40 (current master)

**Comment by rumkex** [comment]
Thanks for reporting! Should be fixed now.
